import './globals.scss';
import type { Metadata } from 'next';
import { League_Spartan } from 'next/font/google';
import Navbar from '@/components/Navbar/Navbar';
import SideBar from '@/components/SideBar/SideBar';

const spartan = League_Spartan({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spartan.className}>
        <div className="globalContainer">
          <main className="container">
            <Navbar />
            <div className="main">
              <SideBar />
              <div className="pageContent"> {children}</div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
